export {default as MoneyIncomeIcon} from './money-income.svg'
export {default as DollarBgIcon} from './dollar-bg.svg'
export {default as SimpleCoinIcon} from './coin.svg'
export {default as CoinsIcon} from './coins.svg'
export {default as BanknoteIcon} from './banknote.svg'