import './globals.css'

import AppLayoutContainer from './app-layout-container'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AppLayoutContainer>{children}</AppLayoutContainer>
    </html>
  )
}
